version: '3'

services:
  tg_notion_bot:
    build: .
    restart: always  # 改为 always 确保任何情况下都会重启
    container_name: tg_notion_bot
    environment:
      - TZ=Asia/Shanghai
      - ZOTERO_PDF_PATH=/zotero/pdfs
      # 代理核心配置
      - http_proxy=http://host.docker.internal:7890 
      - https_proxy=http://host.docker.internal:7890
      - all_proxy=socks5://host.docker.internal:7890
      # 添加保活设置
      - KEEP_ALIVE=true
      - RETRY_INTERVAL=30
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy_network
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
      - /Users/wangruochen/Zotero/storage/pdfs:/zotero/pdfs:ro
    # 启用健康检查
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org')"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    # 启动命令优化
    command: 
      - sh
      - -c
      - |
        # 双模式检测（TCP+HTTP）
        until (timeout 1 bash -c "echo > /dev/tcp/host.docker.internal/7890") || \
              curl -sSf http://host.docker.internal:7890 >/dev/null; do
          echo '等待代理服务就绪...';
          sleep 3;
        done
        exec python main.py

networks:
  proxy_network:
    driver: bridge
