version: '3'

services:
  tg_notion_bot:
    build: .
    restart: unless-stopped
    container_name: tg_notion_bot
    environment:
      - TZ=Asia/Shanghai
      - ZOTERO_PDF_PATH=/zotero/pdfs
      # 代理核心配置
      - http_proxy=http://host.docker.internal:7890 
      - https_proxy=http://host.docker.internal:7890
      - all_proxy=socks5://host.docker.internal:7890
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # network_mode: "host"  # 使用主机网络模式，直接访问本地代理
    networks:
      - proxy_network
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
      - /Users/wangruochen/Zotero/storage/pdfs:/zotero/pdfs:ro
    # 启动命令优化
    command: 
      - sh
      - -c
      - |
        # 双模式检测（TCP+HTTP）
        until (timeout 1 bash -c "echo > /dev/tcp/host.docker.internal/7890") || \
              curl -sSf http://host.docker.internal:7890 >/dev/null; do
          echo '等待代理服务就绪...';
          sleep 3;
        done
        exec python main.py

networks:
  proxy_network:
    driver: bridge
